<a href="https://colab.research.google.com/github/ojohnso3-oss/ojohnso3-INST414/blob/main/Lab13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
md1_df = pd.read_csv("/content/sample_data/prediction_model_01.csv", index_col="imdb_id")

In [3]:
md1_df

              predicted                    actual genres  correct?
imdb_id
tt10880158       Sci-Fi                       ['Comedy']         0
tt0462573   Documentary             ['Drama', 'Romance']         0
tt2160413     Adventure                        ['Drama']         0
tt6032704        Action                       ['Horror']         0
tt2198235   Documentary     ['Action', 'Crime', 'Drama']         0
...                 ...                              ...       ...
tt9701676       History                        ['Drama']         0
tt2718440       Western             ['Action', 'Comedy']         0
tt1954204     Biography                        ['Drama']         0
tt2554842       Musical  ['Drama', 'Horror', 'Thriller']         0
tt1492959        Sci-Fi                        ['Drama']         0

[1885 rows x 3 columns]

In [4]:
acc_md1 = md1_df["correct?"].sum() / md1_df.shape[0]
acc_md1

np.float64(0.08594164456233422)

In [6]:
md2_df = pd.read_csv("/content/sample_data/prediction_model_02.csv", index_col="imdb_id")
md3_df = pd.read_csv("/content/sample_data/prediction_model_03.csv", index_col="imdb_id")

In [7]:
md1_df["predicted"].value_counts()

predicted
Documentary    102
Action          94
Reality-TV      90
Short           89
Adventure       86
News            85
Music           84
Horror          83
Drama           82
Western         82
Crime           81
Family          81
Romance         78
Musical         76
Animation       74
Thriller        74
Sport           73
Mystery         71
Sci-Fi          70
Comedy          69
History         68
Fantasy         68
War             66
Biography       59
Name: count, dtype: int64

In [8]:
md2_df["predicted"].value_counts()

predicted
Drama          1013
Comedy          311
Action          175
Horror          162
Thriller        101
Documentary      70
Animation        13
Crime            11
Adventure         9
Biography         6
Romance           5
Mystery           3
Family            3
Western           2
Sci-Fi            1
Name: count, dtype: int64

In [9]:
md3_df["predicted"].value_counts()

predicted
Drama    1885
Name: count, dtype: int64

Calculate Metrics Per Genre

In [10]:
md1_df["predicted"].value_counts()

predicted
Documentary    102
Action          94
Reality-TV      90
Short           89
Adventure       86
News            85
Music           84
Horror          83
Drama           82
Western         82
Crime           81
Family          81
Romance         78
Musical         76
Animation       74
Thriller        74
Sport           73
Mystery         71
Sci-Fi          70
Comedy          69
History         68
Fantasy         68
War             66
Biography       59
Name: count, dtype: int64

In [11]:
md2_df["predicted"].value_counts()

predicted
Drama          1013
Comedy          311
Action          175
Horror          162
Thriller        101
Documentary      70
Animation        13
Crime            11
Adventure         9
Biography         6
Romance           5
Mystery           3
Family            3
Western           2
Sci-Fi            1
Name: count, dtype: int64

In [12]:
md3_df["predicted"].value_counts()

predicted
Drama    1885
Name: count, dtype: int64

In [13]:
target_genre = "Comedy"

target_model = md1_df

In [14]:
# Precision = tp / (tp + fp)

tp = target_model[target_model["predicted"] == target_genre]["correct?"].sum()
print(tp)

fp = target_model[target_model["predicted"] == target_genre].shape[0] - tp
print(fp)

if (tp + fp) == 0:
    precision = 0
else:
    precision = tp / (tp + fp)
print("Precision:", precision)

21
48
Precision: 0.30434782608695654

In [15]:
# recall = tp / (tp + fn)

target_preds = target_model[target_model["actual genres"].str.contains(target_genre)]
fn = target_preds[target_preds["predicted"] != target_genre].shape[0]
print(fn)

555

In [16]:
recall = tp / (tp + fn)
print("Recall:", recall)

Recall: 0.036458333333333336

In [43]:
tn = target_model.shape[0] -tp - fp - fn
print(tn)
accuracy = (tp + tn) / target_model.shape[0]
print(accuracy)

1591
0.8440318302387267

In [42]:
md1_df["predicted"].value_counts()

predicted
Documentary    102
Action          94
Reality-TV      90
Short           89
Adventure       86
News            85
Music           84
Horror          83
Drama           82
Western         82
Crime           81
Family          81
Romance         78
Musical         76
Animation       74
Thriller        74
Sport           73
Mystery         71
Sci-Fi          70
Comedy          69
History         68
Fantasy         68
War             66
Biography       59
Name: count, dtype: int64

In [41]:
md2_df["predicted"].value_counts()

predicted
Drama          1013
Comedy          311
Action          175
Horror          162
Thriller        101
Documentary      70
Animation        13
Crime            11
Adventure         9
Biography         6
Romance           5
Mystery           3
Family            3
Western           2
Sci-Fi            1
Name: count, dtype: int64

In [39]:
md3_df["predicted"].value_counts()

predicted
Drama    1885
Name: count, dtype: int64

In [40]:
target_genre = "Comedy"

target_model = md1_df

In [38]:
# Precision = tp / (tp + fp)

tp = target_model[target_model["predicted"] == target_genre]["correct?"].sum()
print(tp)

fp = target_model[target_model["predicted"] == target_genre].shape[0] - tp
print(fp)

if (tp + fp) == 0:
    precision = 0
else:
    precision = tp / (tp + fp)
print("Precision:", precision)

0
0
Precision: 0

In [37]:
# recall = tp / (tp + fn)

target_preds = target_model[target_model["actual genres"].str.contains(target_genre)]
fn = target_preds[target_preds["predicted"] != target_genre].shape[0]
print(fn)

294

In [36]:
recall = tp / (tp + fn)
print("Recall:", recall)

Recall: 0.0

In [35]:
f1 = (2* precision * recall) / (precision + recall)
print(f1)

nan

/tmp/ipykernel_2366/4086656291.py:1: RuntimeWarning: invalid value encountered in scalar divide
  f1 = (2* precision * recall) / (precision + recall)

LOOPS

In [34]:
models = {"Model 1": md1_df, "Model 2": md2_df, "Model 3": md3_df}
for model_name, target_model in models.items():
    print()
    print(model_name)
    for target_genre in ["Drama", "Comedy", "Romance", "Horror"]:

          tp = target_model[target_model["predicted"] == target_genre]["correct?"].sum()
          fp = target_model[target_model["predicted"] == target_genre].shape[0] - tp

          if (tp + fp) == 0:
            precision = 0
          else:
            precision = tp / (tp + fp)

          target_preds = target_model[target_model["actual genres"].str.contains(target_genre)]
          fn = target_preds[target_preds["predicted"] != target_genre].shape[0]

          recall = tp / (tp + fn)

          if (precision + recall) == 0:
              f1 = 0
          else:
              f1 = (2* precision * recall) / (precision + recall)

          tn = target_model.shape[0] -tp - fp - fn
          accuracy = (tp + tn) / target_model.shape[0]
          print(f"{target_genre} - Accuracy:, {accuracy:.3f} - Percision:{precision:.3f}, Recall:{recall:.3f}, F1:{f1:.3f}")


print("****"* 20)

Model 1
Drama - Accuracy:, 0.506 - Percision:0.500, Recall:0.044, F1:0.081
Comedy - Accuracy:, 0.680 - Percision:0.304, Recall:0.036, F1:0.065
Romance - Accuracy:, 0.838 - Percision:0.179, Recall:0.055, F1:0.084
Horror - Accuracy:, 0.801 - Percision:0.145, Recall:0.038, F1:0.060

Model 2
Drama - Accuracy:, 0.631 - Percision:0.622, Recall:0.668, F1:0.644
Comedy - Accuracy:, 0.698 - Percision:0.527, Recall:0.280, F1:0.366
Romance - Accuracy:, 0.876 - Percision:0.400, Recall:0.009, F1:0.017
Horror - Accuracy:, 0.855 - Percision:0.599, Recall:0.318, F1:0.415

Model 3
Drama - Accuracy:, 0.498 - Percision:0.498, Recall:1.000, F1:0.665
Comedy - Accuracy:, 0.687 - Percision:0.000, Recall:0.000, F1:0.000
Romance - Accuracy:, 0.866 - Percision:0.000, Recall:0.000, F1:0.000
Horror - Accuracy:, 0.844 - Percision:0.000, Recall:0.000, F1:0.000
********************************************************************************